# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pcu < Formula
  desc ""
  homepage "https://github.com/khanakia/homebrew-pcu"
  version "0.0.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/khanakia/pcu/releases/download/v0.0.2/pcu_Darwin_arm64.tar.gz"
      sha256 "39bde3de9ff5b79d2eaf5183840ba454e93ba6e2c0433c7e5e0ac8d989e6de96"

      def install
        bin.install "pcu"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/khanakia/pcu/releases/download/v0.0.2/pcu_Darwin_x86_64.tar.gz"
      sha256 "b6dcd96e041c711745d60488b60781382fabdb717f1b1e4417a470d29f479e5c"

      def install
        bin.install "pcu"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/khanakia/pcu/releases/download/v0.0.2/pcu_Linux_arm64.tar.gz"
      sha256 "657bfda2de0575ae27967fd315a87230982e5aaa7262a44d2dd853049be7ce30"

      def install
        bin.install "pcu"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/khanakia/pcu/releases/download/v0.0.2/pcu_Linux_x86_64.tar.gz"
      sha256 "fcb59a92bdc8a2bb36bb537b9064f1c673bf063e3c0bd1eb89ee0d9df3b4a350"

      def install
        bin.install "pcu"
      end
    end
  end
end
